// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/shopnow-ecommerce/Cart.tsx": () => import("../components/mockups/shopnow-ecommerce/Cart.tsx"),
  "./components/mockups/shopnow-ecommerce/HomePage.tsx": () => import("../components/mockups/shopnow-ecommerce/HomePage.tsx"),
  "./components/mockups/shopnow-ecommerce/PDP.tsx": () => import("../components/mockups/shopnow-ecommerce/PDP.tsx")
};
